// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                pgtype.UUID `json:"id"`
	UserId            pgtype.UUID `json:"userId"`
	Type              string      `json:"type"`
	Provider          string      `json:"provider"`
	ProviderAccountId string      `json:"providerAccountId"`
	RefreshToken      pgtype.Text `json:"refresh_token"`
	AccessToken       pgtype.Text `json:"access_token"`
	ExpiresAt         pgtype.Int4 `json:"expires_at"`
	TokenType         pgtype.Text `json:"token_type"`
	Scope             pgtype.Text `json:"scope"`
	IDToken           pgtype.Text `json:"id_token"`
	SessionState      pgtype.Text `json:"session_state"`
	OauthTokenSecret  pgtype.Text `json:"oauth_token_secret"`
	OauthToken        pgtype.Text `json:"oauth_token"`
}

type User struct {
	ID            pgtype.UUID        `json:"id"`
	Name          pgtype.Text        `json:"name"`
	Email         pgtype.Text        `json:"email"`
	EmailVerified pgtype.Timestamptz `json:"emailVerified"`
	Image         pgtype.Text        `json:"image"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Coords        interface{}        `json:"coords"`
	Interests     []string           `json:"interests"`
}
