// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkUserExists = `-- name: CheckUserExists :one
SELECT 1 FROM "User" WHERE email = $1
`

// USER QUERIES
func (q *Queries) CheckUserExists(ctx context.Context, email pgtype.Text) (int32, error) {
	row := q.db.QueryRow(ctx, checkUserExists, email)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO "Account" ("userId", "type", "provider", "providerAccountId", "refresh_token", "access_token", "token_type", "scope")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, "userId", type, provider, "providerAccountId", refresh_token, access_token, expires_at, token_type, scope, id_token, session_state, oauth_token_secret, oauth_token
`

type CreateAccountParams struct {
	UserId            string      `json:"userId"`
	Type              string      `json:"type"`
	Provider          string      `json:"provider"`
	ProviderAccountId string      `json:"providerAccountId"`
	RefreshToken      pgtype.Text `json:"refresh_token"`
	AccessToken       pgtype.Text `json:"access_token"`
	TokenType         pgtype.Text `json:"token_type"`
	Scope             pgtype.Text `json:"scope"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.UserId,
		arg.Type,
		arg.Provider,
		arg.ProviderAccountId,
		arg.RefreshToken,
		arg.AccessToken,
		arg.TokenType,
		arg.Scope,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserId,
		&i.Type,
		&i.Provider,
		&i.ProviderAccountId,
		&i.RefreshToken,
		&i.AccessToken,
		&i.ExpiresAt,
		&i.TokenType,
		&i.Scope,
		&i.IDToken,
		&i.SessionState,
		&i.OauthTokenSecret,
		&i.OauthToken,
	)
	return i, err
}

const createLocation = `-- name: CreateLocation :one
INSERT INTO "Location" (coords)
VALUES (ST_Point($1, $2, 4326))
RETURNING id, coords
`

type CreateLocationParams struct {
	StPoint   interface{} `json:"st_point"`
	StPoint_2 interface{} `json:"st_point_2"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation, arg.StPoint, arg.StPoint_2)
	var i Location
	err := row.Scan(&i.ID, &i.Coords)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO "User" ("name", "email", "image", "updated_at")
VALUES ($1, $2, $3, $4)
RETURNING id, name, email, "emailVerified", image, created_at, updated_at
`

type CreateUserParams struct {
	Name      pgtype.Text        `json:"name"`
	Email     pgtype.Text        `json:"email"`
	Image     pgtype.Text        `json:"image"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Image,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLocations = `-- name: ListLocations :many
SELECT id, st_astext(coords) as coords
FROM "Location"
WHERE ST_DWithin(coords, ST_MakePoint($1, $2)::geography, 100)
`

type ListLocationsParams struct {
	StMakepoint   interface{} `json:"st_makepoint"`
	StMakepoint_2 interface{} `json:"st_makepoint_2"`
}

type ListLocationsRow struct {
	ID     pgtype.UUID `json:"id"`
	Coords interface{} `json:"coords"`
}

func (q *Queries) ListLocations(ctx context.Context, arg ListLocationsParams) ([]ListLocationsRow, error) {
	rows, err := q.db.Query(ctx, listLocations, arg.StMakepoint, arg.StMakepoint_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLocationsRow
	for rows.Next() {
		var i ListLocationsRow
		if err := rows.Scan(&i.ID, &i.Coords); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
